"""SQLite lock covers complete contact preview and generated bytes."""
from concurrent.futures import ThreadPoolExecutor
from threading import Event
from types import SimpleNamespace
import unittest
from unittest.mock import patch
from test_clinical_followup_contact_documents import ContactDocumentFixture,FIXTURE,documents,api,doc_text,f

class ContactDocumentConcurrency(ContactDocumentFixture):
    def race(self,action,rendering):
        extra={}
        if action in ('source','source_metadata','lab','imaging','mixed_plan'):
            sources,rows=self.save_pair();self.meta={**self.meta,'kind':'dr'};_,_,image=self.save_image()
            extra={'manual_lab_report_ids':[rows[0]['id']],'manual_imaging_report_ids':[image['id']],'manual_lab_comparison':self.request_body(index=3)}
        row=self.contact_save();choice=self.choice(row);before=self.checked(choice,**extra)
        if action in ('correct','withdraw'):
            body=self.contact_review(self.contact_body(action,row,FIXTURE['corrected']));mutation=lambda:self.client.post(self.contact_root+'/confirm',headers=self.owner_headers,json=body)
        elif action in ('plan_correct','plan_withdraw','mixed_plan'):
            body=self.plan_body('withdraw' if action=='plan_withdraw' else 'correct',self.source,FIXTURE['corrected_plan']);mutation=lambda:self.client.post(self.plan_root+'/confirm',headers=self.owner_headers,json=body)
        elif action in ('source','source_metadata'):
            self.meta={**sources[0]['metadata'],'title':'CW21 并发来源更正'};body=self.reviewed(self.body(sources[0],'withdraw' if action=='source' else 'update'));mutation=lambda:self.commit(body)
        elif action=='lab':
            body=self.lab_review(self.lab_body(old=rows[0],operation='withdraw'));mutation=lambda:self.lab_commit(body)
        elif action=='imaging':
            body=self.image_review(self.image_body(old=image,operation='withdraw'));mutation=lambda:self.image_commit(body)
        elif action=='delete':mutation=lambda:self.client.delete(f'/api/cases/{self.cid}',headers=self.owner_headers)
        elif action=='owner':
            uid=self.contact()['case']['owner_id']
            def mutation():
                with documents.plans.transaction(uid,self.cid) as (db,case):case.owner_id+=1;db.commit()
                return SimpleNamespace(status_code=200)
        else:mutation=lambda:self.client.put(f'/api/cases/{self.cid}',headers=self.owner_headers,json={'owner_name':'CW21 并发身份'} if action=='identity' else {'history':'CW21 并发正文'})
        entered,release,attempted=Event(),Event(),Event()
        module,method=(api,'_render_docx') if rendering else (documents,'read_selected');normal=getattr(module,method)
        def held(*args,**kwargs):entered.set();assert release.wait(15);return normal(*args,**kwargs)
        def mutate():attempted.set();return mutation()
        with ThreadPoolExecutor(2) as pool,patch.object(module,method,side_effect=held):
            reading=pool.submit(self.document,choice,'render' if rendering else 'render-preview',before['content_snapshot'] if rendering else None,**extra)
            try:
                self.assertTrue(entered.wait(10));writing=pool.submit(mutate);self.assertTrue(attempted.wait(10));self.assertFalse(writing.done())
            finally:release.set()
            r=reading.result(20);self.assertEqual(r.status_code,200,r.text[:200] if not rendering else '')
            if rendering:self.assertIn(row['data']['note'],doc_text(r.content));self.assertNotIn('CW21 并发正文',doc_text(r.content))
            else:self.assertEqual(r.json()['content_snapshot'],before['content_snapshot'])
            self.assertEqual(writing.result(20).status_code,204 if action=='delete' else 200)
        self.assertEqual(self.document(choice,'render',before['content_snapshot'],**extra).status_code,404 if action in ('delete','owner') else 409)

for action in ('correct','withdraw','plan_correct','plan_withdraw','body','identity','delete','owner','source','source_metadata','lab','imaging','mixed_plan'):
    for rendering in (False,True):
        setattr(ContactDocumentConcurrency,f'test_{action}_{"render" if rendering else "preview"}',lambda self,a=action,r=rendering:self.race(a,r))
if __name__=='__main__':unittest.main(verbosity=2)
