// Real Chromium / React / FastAPI / PostgreSQL; only named response-drop and
// GET-failure checks intercept traffic. No successful response is fabricated.
const {chromium, expect}=require('@playwright/test');
const assert=require('node:assert/strict'), fs=require('node:fs'), path=require('node:path');
const UI='http://127.0.0.1:5173', API='http://127.0.0.1:18026';
const out=process.env.PMAI_ACCEPTANCE_OUT;
assert(out && process.env.PMAI_SYNTHETIC_ACCEPTANCE==='PR26');
let browser,context,page,auth,cid,sid;
const passed=[],failures=[],external=[],pageErrors=[],writes=[];
const update=()=>page.getByRole('region',{name:'更新已绑定病例核对',exact:true});
const save=()=>page.getByRole('region',{name:'首次保存病例核对',exact:true});
const note=()=>page.getByPlaceholder('例如：复诊补充的症状、用药经过、主人新提供的病史',{exact:true});
const history=()=>page.locator('label').filter({has:page.getByText('既往史',{exact:true})}).locator('textarea');
const step=n=>page.getByRole('navigation',{name:'问诊工作台步骤',exact:true}).getByRole('button',{name:['问诊整理','保存前核对','病例回看'][n-1],exact:true});
const next=suffix=>page.waitForResponse(r=>r.request().method()==='POST' && new URL(r.url()).pathname.endsWith(suffix));
async function api(method,route,data){assert(route.startsWith('/api/'));const r=await context.request.fetch(API+route,{method,headers:auth,data});assert.equal(r.status(),200,await r.text());return r.json();}
async function record(name){passed.push(name);console.log('PASS:',name);await page.screenshot({path:path.join(out,`addendum-${passed.length}-${name}.png`),fullPage:true});}
async function audit(){await page.getByPlaceholder('如 HS-0001 / Dr.Zhao',{exact:true}).fill('Synthetic-Addendum');const r=next('/api/audit-log');await page.getByRole('button',{name:'确认覆核并写入审计',exact:true}).click();assert.equal((await r).status(),201);await expect(page.getByRole('button',{name:'审计已写入',exact:true})).toBeVisible();}
async function preview(){await step(2).click();const r=next('/preview-update-case');await update().getByRole('button',{name:/^(核对更新内容|重新预览更新内容)$/}).click();const p=await (await r).json();await update().getByLabel('已核对本次更新内容',{exact:true}).check();return p;}
async function verifySaved(){await expect(step(3)).toHaveAttribute('aria-current','step');const current=await api('GET','/api/cases/'+cid);await expect(page.getByRole('region',{name:'本次保存回读',exact:true}).getByRole('region',{name:'完整病史',exact:true}).locator('pre')).toHaveText(current.history,{useInnerText:false});return current;}
async function main(){
 browser=await chromium.launch({headless:true});console.log('Chromium addendum acceptance:',browser.version());
 context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
 await context.route('**/*',route=>{const origin=new URL(route.request().url()).origin;if([UI,API].includes(origin))return route.continue();external.push(origin);return route.abort();});
 page=await context.newPage();page.on('dialog',d=>d.accept());page.on('pageerror',e=>pageErrors.push(e.message));page.on('request',r=>{if(r.method()==='POST' && new URL(r.url()).pathname.endsWith('/update-case'))writes.push(r.postDataJSON());});
 await page.goto(UI);await page.getByPlaceholder('邮箱',{exact:true}).fill('browser-owner@example.com');await page.getByPlaceholder('密码',{exact:true}).fill('Synthetic-PR26-only-20260916');
 let r=next('/auth/login');await page.getByRole('button',{name:'登录',exact:true}).click();assert.equal((await r).status(),200);await expect(page.getByRole('button',{name:'退出',exact:true})).toBeVisible();auth={Authorization:'Bearer '+await page.evaluate(()=>localStorage.getItem('token'))};
 await page.getByPlaceholder('如：乐乐 / Lucky',{exact:true}).fill('医生补记合成犬');await page.getByLabel('主诉（必填）',{exact:true}).fill('合成犬呕吐两次，精神正常');await history().fill('既有病史原文🐾\n不能丢失。  \n');
 r=next('/api/ai/consult/session');await page.getByRole('button',{name:'提交分析（不入库）',exact:true}).click();sid=(await (await r).json()).session_id;
 await audit();await step(2).click();r=next('/preview-case');await save().getByRole('button',{name:'核对保存内容',exact:true}).click();await r;await save().getByLabel('已核对本次保存内容',{exact:true}).check();await save().getByRole('button',{name:'确认并保存病例',exact:true}).click();await expect(step(3)).toHaveAttribute('aria-current','step');cid=(await api('GET','/api/ai/consult/session/'+sid)).case_id;
 const original=await api('GET','/api/cases/'+cid), text='  复诊新增病史🐾\n保留末尾空格。  \n';
 await step(1).click();await note().fill(text);let p=await preview();
 assert.equal(p.history_addendum,text);assert(p.proposed.history.startsWith(original.history));assert(p.proposed.history.endsWith('【医生病史补记】\n'+text));assert.deepEqual(await api('GET','/api/cases/'+cid),original);assert.equal(writes.length,0);
 await expect(update().getByRole('region',{name:'本次医生病史补记',exact:true}).locator('pre')).toHaveText(text,{useInnerText:false});await record('note_preview_preserves_existing_without_writes');
 await step(1).click();await note().fill(text+'第二句新增');await step(2).click();await expect(update().getByRole('button',{name:'确认并更新病例',exact:true})).toHaveCount(0);assert.equal(writes.length,0);await record('changed_note_requires_fresh_confirmation');
 p=await preview();await update().getByRole('button',{name:'确认并更新病例',exact:true}).click();let current=await verifySaved();assert.equal(current.history,p.proposed.history);assert.equal(writes.length,1);await expect(page.getByText('当前输入另有修改，尚未保存；下方仍是上次回读的病例内容。',{exact:true})).toHaveCount(0);await step(1).click();await expect(note()).toHaveValue('');await record('confirmed_note_save_readback_and_clear');
 const second='刷新后继续保存的第二份补记';await note().fill(second);await page.reload();const draft=page.getByRole('region',{name:'本标签页草稿',exact:true});await draft.getByRole('button',{name:'恢复本页草稿',exact:true}).click();await expect(draft.getByText('发现本页未完成草稿',{exact:true})).toHaveCount(0);await expect(note()).toHaveValue(second);await step(2).click();await expect(update().getByRole('button',{name:'核对更新内容',exact:true})).toBeDisabled();assert.equal((await api('GET','/api/cases/'+cid)).history,current.history);await record('note_draft_refresh_requires_reaudit');
 await step(1).click();await audit();p=await preview();const externalHistory=current.history+'\n另一医生已经保存的记录';await api('PUT','/api/cases/'+cid,{history:externalHistory});r=next('/update-case');await update().getByRole('button',{name:'确认并更新病例',exact:true}).click();assert.equal((await r).status(),409);await expect(update()).toContainText('原确认已失效');assert.equal((await api('GET','/api/cases/'+cid)).history,externalHistory);await step(1).click();await expect(note()).toHaveValue(second);await record('stale_note_preview_does_not_overwrite_external_change');
 p=await preview();const writeCount=writes.length, route='**/api/ai/consult/session/'+sid+'/update-case';await page.route(route,async handler=>{const real=await handler.fetch();assert.equal(real.status(),200);await handler.abort('failed');});await update().getByRole('button',{name:'确认并更新病例',exact:true}).click();current=await verifySaved();await page.unroute(route);assert.equal(writes.length,writeCount+1);assert.equal(current.history,p.proposed.history);assert(current.history.startsWith(externalHistory));await record('lost_note_save_response_get_readback_no_second_write');
 await step(1).click();await note().fill('第三份补记：已提交但回读故障');p=await preview();const caseRoute='**/api/cases/'+cid;await page.route(caseRoute,handler=>handler.request().method()==='GET'?handler.abort('failed'):handler.continue());const beforeFailed=writes.length;await update().getByRole('button',{name:'确认并更新病例',exact:true}).click();await expect(update()).toContainText('暂时无法回读病例');await step(1).click();await expect(note()).toHaveValue('第三份补记：已提交但回读故障');assert.equal((await api('GET','/api/cases/'+cid)).history,p.proposed.history);await record('failed_note_readback_keeps_input');
 await note().fill('第四份补记：尚未提交的更新内容');await step(2).click();await page.unroute(caseRoute);await update().getByRole('button',{name:'核对保存结果',exact:true}).click();current=await verifySaved();assert.equal(writes.length,beforeFailed+1);assert.equal(current.history,p.proposed.history);await expect(page.getByText('当前输入另有修改，尚未保存；下方仍是上次回读的病例内容。',{exact:true})).toBeVisible();await step(1).click();await expect(note()).toHaveValue('第四份补记：尚未提交的更新内容');await record('retry_readback_preserves_newer_note_input');
 await page.goto(UI+'/cases/'+cid);await page.reload();const full=page.getByRole('region',{name:'完整病史原文',exact:true});await expect(full).toBeVisible();assert.equal(await full.locator('pre').textContent(),current.history);assert(!current.history.includes('第四份补记'));assert.deepEqual(external,[]);assert.deepEqual(pageErrors,[]);await record('case_detail_refresh_shows_full_saved_addenda');
}
main().then(()=>{process.exitCode=0;}).catch(async error=>{process.exitCode=1;console.error(error);failures.push(String(error));if(page){await page.screenshot({path:path.join(out,'addendum-failure.png'),fullPage:true}).catch(()=>{});fs.writeFileSync(path.join(out,'addendum-failure-dom.txt'),await page.locator('body').innerText().catch(()=>''));}}).finally(async()=>{fs.writeFileSync(path.join(out,'addendum-checks.json'),JSON.stringify({passed,failures,pageErrors,external},null,2));if(browser)await browser.close();});
