// Real Chromium, React, FastAPI and disposable native PostgreSQL.
// Fault cases only drop actual save responses or block GET; no fabricated success.
const {chromium,expect}=require('@playwright/test');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const UI='http://127.0.0.1:5173',API='http://127.0.0.1:18026',out=process.env.PMAI_ACCEPTANCE_OUT;
assert(out && process.env.PMAI_SYNTHETIC_ACCEPTANCE==='PR26');
let browser,context,page,auth,cid;const passed=[],failures=[],external=[],pageErrors=[],writes=[];
const review=()=>page.getByRole('region',{name:'病例修改核对',exact:true});
const field=label=>page.locator('label').filter({has:page.getByText(label,{exact:true})}).locator('textarea');
const treatment=()=>field('治疗建议');
const history=()=>field('既往史 / 动态问诊追问记录');
const next=suffix=>page.waitForResponse(r=>r.request().method()==='POST' && new URL(r.url()).pathname.endsWith(suffix));
async function api(method,route,data){assert(route.startsWith('/api/'));const r=await context.request.fetch(API+route,{method,headers:auth,data});assert.equal(r.status(),method==='POST'&&route==='/api/cases'?201:200,await r.text());return r.json();}
async function record(name){passed.push(name);console.log('PASS:',name);await page.screenshot({path:path.join(out,`editor-${passed.length}-${name}.png`),fullPage:true});}
async function preview(){const r=next('/preview-edit');await review().getByRole('button',{name:/^(核对修改内容|重新核对修改)$/}).click();const response=await r;assert.equal(response.status(),200,await response.text());const p=await response.json();await review().getByLabel('已核对本次病例修改',{exact:true}).check();return p;}
async function verify(){await expect(review().getByRole('region',{name:'修改后服务器回读',exact:true})).toBeVisible();return api('GET','/api/cases/'+cid);}
async function main(){
 browser=await chromium.launch({headless:true});console.log('Chromium editor acceptance:',browser.version());
 context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
 await context.route('**/*',route=>{const origin=new URL(route.request().url()).origin;if([UI,API].includes(origin))return route.continue();external.push(origin);return route.abort();});
 page=await context.newPage();page.on('pageerror',e=>pageErrors.push(e.message));page.on('request',r=>{if(r.method()==='POST' && new URL(r.url()).pathname.endsWith('/confirm-edit'))writes.push(r.postDataJSON());});
 await page.goto(UI);await page.getByPlaceholder('邮箱',{exact:true}).fill('browser-owner@example.com');await page.getByPlaceholder('密码',{exact:true}).fill('Synthetic-PR26-only-20260916');
 let r=next('/auth/login');await page.getByRole('button',{name:'登录',exact:true}).click();assert.equal((await r).status(),200);await expect(page.getByRole('button',{name:'退出',exact:true})).toBeVisible();auth={Authorization:'Bearer '+await page.evaluate(()=>localStorage.getItem('token'))};
 cid=(await api('POST','/api/cases',{patient_name:'编辑闭环合成犬',species:'dog',chief_complaint:'  医生确认主诉🐾\r\n ',history:'  医生病史原文🐾\r\n尾部空格。  \n',exam_findings:'  体检原文\r\n '})).id;
 await api('PUT','/api/cases/'+cid,{analysis:'医生分析',treatment:'原治疗',prognosis:'医生风险'});const original=await api('GET','/api/cases/'+cid);
 await page.goto(UI+'/cases/'+cid);await page.getByRole('link',{name:'编辑',exact:true}).click();await expect(review().getByRole('button',{name:'核对修改内容',exact:true})).toBeDisabled();assert.equal(writes.length,0);
 await treatment().fill('  编辑新增治疗🐾\n ');let p=await preview();assert.deepEqual(Object.keys(p.changes),['treatment']);assert.equal(p.proposed.history,original.history);assert.deepEqual(await api('GET','/api/cases/'+cid),original);assert.equal(writes.length,0);await record('editor_preview_only_changed_fields_without_write');
 await treatment().fill('医生重新核对后的治疗');await expect(review().getByRole('button',{name:'确认并保存修改',exact:true})).toHaveCount(0);assert.equal(writes.length,0);await record('editor_input_change_invalidates_confirmation');
 p=await preview();await review().getByRole('button',{name:'确认并保存修改',exact:true}).click();let current=await verify();for(const [key,value] of Object.entries(p.proposed))assert.equal(current[key],value,key);for(const key of Object.keys(original))if(key!=='treatment')assert.deepEqual(current[key],original[key],key);assert.equal(writes.length,1);assert.deepEqual(Object.keys(writes[0].changes),['treatment']);await record('editor_save_readback_preserves_untouched_history_bytes');
 await treatment().fill('冲突后保留的医生治疗');const newer=current.history+'\n其他医生追加病史';await api('PUT','/api/cases/'+cid,{history:newer});r=next('/preview-edit');await review().getByRole('button',{name:'重新核对修改',exact:true}).click();assert.equal((await r).status(),409);await expect(treatment()).toHaveValue('冲突后保留的医生治疗');await review().getByRole('button',{name:'读取最新病例并保留本次修改',exact:true}).click();await expect(history()).toHaveValue(newer.replace(/\r\n/g,'\n'));await expect(treatment()).toHaveValue('冲突后保留的医生治疗');assert.equal(writes.length,1);await record('editor_stale_open_reloads_server_and_keeps_doctor_changes');
 p=await preview();await api('PUT','/api/cases/'+cid,{owner_phone:'synthetic-external-change'});r=next('/confirm-edit');await review().getByRole('button',{name:'确认并保存修改',exact:true}).click();assert.equal((await r).status(),409);await expect(review()).toContainText('原确认失效');await expect(treatment()).toHaveValue('冲突后保留的医生治疗');assert.equal((await api('GET','/api/cases/'+cid)).treatment,current.treatment);await record('editor_stale_confirmation_refuses_overwrite');
 await review().getByRole('button',{name:'读取最新病例并保留本次修改',exact:true}).click();await expect(review()).toContainText('已读取最新病例');p=await preview();const writeRoute='**/api/cases/'+cid+'/confirm-edit',n=writes.length;await page.route(writeRoute,async handler=>{const real=await handler.fetch();assert.equal(real.status(),200);await handler.abort('failed');});await review().getByRole('button',{name:'确认并保存修改',exact:true}).click();current=await verify();await page.unroute(writeRoute);assert.equal(writes.length,n+1);assert.equal(current.treatment,p.proposed.treatment);assert.equal(current.history,newer);await record('editor_lost_response_get_readback_without_second_write');
 await treatment().fill('保存成功但回读故障后的治疗');p=await preview();const getRoute='**/api/cases/'+cid+'/edit-state';await page.route(getRoute,handler=>handler.abort('failed'));const beforeFailed=writes.length;await review().getByRole('button',{name:'确认并保存修改',exact:true}).click();await expect(review()).toContainText('保存结果待核对');await expect(treatment()).toHaveValue('保存成功但回读故障后的治疗');await expect(treatment()).toBeDisabled();assert.equal((await api('GET','/api/cases/'+cid)).treatment,p.proposed.treatment);await page.unroute(getRoute);await review().getByRole('button',{name:'核对保存结果',exact:true}).click();current=await verify();assert.equal(writes.length,beforeFailed+1);await record('editor_failed_readback_preserves_input_and_retries_get_only');
 await review().getByRole('link',{name:'查看已保存病例 #'+cid,exact:true}).click();await page.reload();const full=page.getByRole('region',{name:'完整病史原文',exact:true}).locator('.text-body');await expect(full).toBeVisible();assert.equal(await full.textContent(),current.history);assert.equal(current.chief_complaint,original.chief_complaint);assert.equal(current.exam_findings,original.exam_findings);assert.equal(current.owner_phone,'synthetic-external-change');assert.deepEqual(external,[]);assert.deepEqual(pageErrors,[]);await record('editor_detail_refresh_matches_saved_content');
}
main().then(()=>{process.exitCode=0;}).catch(async error=>{process.exitCode=1;console.error(error);failures.push(String(error));if(page){await page.screenshot({path:path.join(out,'editor-failure.png'),fullPage:true}).catch(()=>{});fs.writeFileSync(path.join(out,'editor-failure-dom.txt'),await page.locator('body').innerText().catch(()=>''));}}).finally(async()=>{fs.writeFileSync(path.join(out,'editor-checks.json'),JSON.stringify({passed,failures,pageErrors,external},null,2));if(browser)await browser.close();});
