name: Validate KB
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'knowledge-base/**'
      - 'tools/validate_kb.py'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python tools/validate_kb.py
